import Head from "next/head";
import React from "react";

const SEO = () => {
  return (
    <Head>
      <meta charSet="utf-8" />
      <meta name="theme-color" content="#ffffff" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <meta rel="icon" href="/favicon.ico" />
      <title>RapidAPI - Weather News App</title>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
};

export default SEO;
